### ISSUE TITLE
Temporal Jitter while window is in focus on Yosemite

### ISSUE THREAD

**Issue by Aerotune** [jlnr/gosu#269]
I've run into a little weird problem which makes the animations jagged.

Reproduction:
* Run the script below in Ruby.app
* See jitter in movement
* Switch to another App (Finder, Activity Monitor)
* See completely smooth movement in Ruby.app in the background
* Switch back to Ruby.app
* See jitter in movement

I'm using the packaged .app with Ruby 2.1.2, Gosu 0.7.50 and Mac OS 10.10.2 (14C109).

```
require 'gosu'

class Window < Gosu::Window
  def initialize
    super 800, 600, false
    self.caption = "Temporal Jitter Test"
    @font = Gosu::Font.new self, 'Arial', 24
    @x = 0
  end
  
  def update
    @x = (@x + 8) % width
    #@x = (Time.now.to_f * 60.0 * 8.0) % width # <= yields same results
    #@x = (Gosu.milliseconds * 0.06 * 8.0) % width # <= yields same results
  end
  
  def draw
    @font.draw "Smooth Moves", @x, 10, 0
  end
end

Window.new.show
```

**Comment by jlnr** [comment]
Hmm crap, I won't be able to update to Yosemite until April. I suppose it will help to update the `Ruby.app` to Gosu 0.8.0. I've been meaning to wait for a stable SDL 2.0.4 release, but maybe I should go ahead. Thanks for reporting this! And kinda sad that you are the first to report this - there don't seem to be many packaged Ruby games in the wild. ;)

**Comment by jlnr** [comment]
I'm on Yosemite now. Getting there... :/

**Comment by jlnr** [comment]
Should be fixed with the latest release. Thanks for reporting this!

https://github.com/gosu/ruby-app/releases
