### ISSUE TITLE
Mouse position lag

### ISSUE THREAD

**Issue by RavensKrag** [jlnr/gosu#272]
Window#mouse_x and #mouse_y appear to lag behind by a frame or so. Not sure if this effects other forms of input or not, but this issue is most noticeable with mouse input.

Run this code for an example:
https://gist.github.com/RavensKrag/9e5dc04596537de7a471
(example requires Chipmunk to make it cleaner to express vert positions)

Move your mouse in a large circle, and notice how the yellow square trails behind the cursor. The amount it trails behind is related to the speed at which the cursor is moved, suggesting some sort of off-by-one error, or similar.

Tested using Gosu 0.8.7.2 on Ubuntu Linux 14.04 x64, ruby 2.1.1p76, RVM,

**Comment by RavensKrag** [comment]
Wait, shoot. this appears to be an issue with the graphics stack on my machine. I'll re-open this later if I notice it's still a problem, once I upgrade everything.

(I won't be able to do that for another month or so, though)

**Comment by jlnr** [comment]
No worries. Just for reference, internally it works like this:

- Gosu fetches the current mouse position from SDL
- `Window#update`
- `Window#draw`
- wait for next frame

So if there is any lag, it is probably happening on the SDL side of things.
